version: '3'
services:
  triplan:
    image: 'softwaremill/triplan:latest'
    ports:
      - '8080:8080'
    depends_on:
      - triplan-db
    environment:
      SQL_USERNAME: 'postgres'
      SQL_PASSWORD: 'b00t200k4'
      SQL_DBNAME: 'triplan'
      SQL_HOST: 'triplan-db'
      SQL_PORT: '5432'
      API_HOST: '0.0.0.0'
  triplan-db:
    image: 'postgres'
    ports:
      - '25432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'b00t200k4'
      POSTGRES_DB: 'triplan'
