version: "3.7"

services:
  app:
    build: .
    restart: always
    env_file:
      - .env
    command: >
      sh -c 'dockerize -wait tcp://mongodb:27017 -timeout 60s && node dist/server.js'
    depends_on:
      - mongodb
    networks:
      - app-network
    ports:
      - "8080:8080"
    volumes:
      - ./private.key:/private.key
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file:
      - .localenv
    volumes:
      - ./backend/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./triData:/data/db
      - ./backend/resources/plans:/plans
    networks:
      - app-network
    ports:
      - "27017:27017"
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - app
    networks:
      - app-network
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - app
    command: certonly --webroot --webroot-path=/var/www/html --email sonag007@gmail.com --agree-tos --no-eff-email --staging -d triplan.club  -d www.triplan.club
  telegram-bot:
    build: telegram
    env_file:
      - .env
    depends_on:
      - app
    networks: 
      - app-network

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /Users/andriisumko/git/triplan/client/public/
      o: bind

networks:
  app-network:
    driver: bridge
