version: "3.7"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: triadmin
      MONGO_INITDB_ROOT_PASSWORD: pa$Sw0rd
      MONGO_INITDB_DATABASE: triplan
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./triData:/data/db
