name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]
jobs:
  lint-and-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        uses: CultureHQ/actions-yarn@master
        working-directory: backend
        with:
          args: install
        run: yarn install
      - name: Test
        uses: CultureHQ/actions-yarn@master
        with:
          args: test
