name: Test
# This workflow is triggered on pushes to the repository.
on: [push]
jobs:
  lint-and-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Install
        working-directory: backend
        run: yarn install
      - name: Linting
        working-directory: backend
        run: yarn lint
      - name: Test
        working-directory: backend
        run: yarn test
