name: Publish
on:
  push:
    branches:
      - master
jobs:
  build-and-publish:
    name: Building and publishing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: build and publish
        run: |
          yarn --cwd client install
          yarn --cwd backend install
          make build-docker
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: sonac/triplan/triplan
          tag_with_ref: true
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          envs: GITHUB_USERNAME, GITHUB_TOKEN
          script: |
            cd app
            /snap/bin/docker-compose down 
            /snap/bin/docker login docker.pkg.github.com -u $GITHUB_USERNAME -p $GITHUB_TOKEN
            /snap/bin/docker pull docker.pkg.github.com/sonac/triplan/triplan:latest
            /snap/bin/docker-compose up -d
