name: Publish
on:
  push:
    branches:
      - master
jobs:
  lint-and-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: build and publish
        run: |
          yarn --cwd client install
          yarn --cwd backend install
          make ci-docker-login  
          make publish
