name: Publish
on:
  push:
    branches:
      - master
jobs:
  build-and-publish:
    name: Building and publishing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: build and publish
        run: |
          yarn --cwd client install
          yarn --cwd backend install
          make build-docker
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: sonac/triplan/triplan
          tag_with_ref: true
